version: '3.8'

services:
  web:
    image: php:7.4-apache
    container_name: eco_services_web
    ports:
      - "80:80"
    volumes:
      - ./back-end/public:/var/www/html
      - ./style.css:/var/www/html/style.css
      - ./back-end/config/db.php:/var/www/html/config/db.php
    depends_on:
      - db
    networks:
      - eco-services-network

  db:
    image: mysql:5.7
    container_name: eco_services_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: eco_services
      MYSQL_USER: eco_user
      MYSQL_PASSWORD: eco_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - eco-services-network

  nginx:
    image: nginx:latest
    container_name: eco_services_nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./back-end/public:/var/www/html
    depends_on:
      - web
    networks:
      - eco-services-network

volumes:
  db_data:

networks:
  eco-services-network:
    driver: bridge
