name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: docker/cache-action@v2
        with:
          path: /tmp/.buildx-cache
      
      - name: Build Docker image
        run: |
          docker build -t xedicus13/eco-services:latest .
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push Docker image
        run: |
          docker push xedicus13/eco-services:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v2
        with:
          version: '1.21.0'

      - name: Deploy to Kubernetes
        run: |
           kubectl apply -f ../../k8s-deployment/config.yaml
           kubectl apply -f ../../k8s-deployment/deployment.yaml
           kubectl apply -f ../../k8s-deployment/ingress.yaml
           kubectl apply -f ../../k8s-deployment/maria-deployment.yaml
           kubectl apply -f ../../k8s-deployment/service.yaml
           kubectl rollout restart deployment eco-services-deployment
